blog/urls.py
from django.urls import path, include

from .views import blog, profile, BlogLoginView, BlogLogoutView, RegisterUserView, RegisterDoneView
from .views import add_story, page_story, story_done


app_name = "blog"

urlpatterns = [
    path("accounts/register/done/", RegisterDoneView.as_view(), name="register_done"),
    path("accounts/register/", RegisterUserView.as_view(), name="register"),
    path("accounts/logout/", BlogLogoutView.as_view(), name="logout"),  # log out of account
    path("accounts/profile/", profile, name="profile"),
    path("accounts/login/", BlogLoginView.as_view(), name="login"),  # page 'login'
    path("add_story/", add_story, name="add_story"),  # page 'add_story'
    path("page_story/<id_story>", page_story, name="page_story"),  # page "page_story"
    path("story_done", story_done, name="story_done"),  # page "story_done"
    path("", blog, name="blog"),  # home page 'blog'
]

main/urls.py
from django.urls import path, include

from .views import index

app_name = "main"

urlpatterns = [
    path("", index, name="index"),  # home page
]

resume/urls.py
from django.contrib import admin
from django.urls import path, include

# no cache for static-files
# [rus] для того чтобы на разработке не кэшировались файлы в обозревателе
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path("", include("main.urls", namespace="")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("visitka/", include("visitka.urls", namespace="visitka")),
    path('admin/', admin.site.urls),
]

# no cache for static-files
# [rus] для того чтобы на разработке не кэшировались файлы в обозревателе
if settings.DEBUG:
    urlpatterns.append(path("static/<path:path>", never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visitka/urls.py
from django.urls import path, include
from .views import visitka

app_name = "visitka"

urlpatterns = [    
    path("", visitka, name="visitka"),  # home page 'visitka'
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

from .utilites import get_timestamp_path


# Model for stories (secondary to User)
# [rus] Модель для рассказов (вторична для User)
class Story(models.Model):
    # link to the author
    # [rus] ссылка на автора
    stories = models.ForeignKey(User, on_delete=models.CASCADE,
                                verbose_name="Автор рассказа")
    # story name (unique, indexed by field)
    # [rus] имя рассказа (уникально, создан индекс по полю)
    title_story = models.TextField(max_length=50, unique=True,
                                   verbose_name="Название")
    # first 1000 characters from the story (optional)
    # [rus] первые 1000 символов из рассказа (необязательно)
    text_small = models.TextField(max_length=1000, blank=True,
                                  verbose_name="Предпросмотр")
    # unloaded file with story content (path: "stories/%Y/%m/%d/", name: "time.file_type")
    # [rus] выгружаемый файл с содержимым рассказа (путь: "stories/%Y/%m/%d/", имя: "время.тип_файла")
    text_file = models.FileField(upload_to=get_timestamp_path,
                                 verbose_name="Рассказ")
    # picture for the story (optional)
    # [rus] картинка к рассказу (необязательно)
    image_story = models.ImageField(upload_to=get_timestamp_path, blank=True,
                                    verbose_name="Обложка")

    # returns username from User by primary key
    # [rus] возвращает username из User по первичному ключу
    def get_author(self, parent_id):
        return User.objects.get(id=parent_id).username

    class Meta:
        verbose_name = "Рассказ"
        verbose_name_plural = "Рассказы"

visitka/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from django.forms.widgets import TextInput
from .models import Story
from .validators import validate_file_extension, validate_file_size


# Form for adding a story
# [rus] Форма добавления рассказа
class StoryForm(forms.ModelForm):
    text_file = forms.FileField(validators=[validate_file_extension, validate_file_size])

    class Meta:
        model = Story  # the model used
        fields = ("title_story", "text_file", "image_story")  # displayed fields in the form
        labels = {"title_story": "Название рассказа", "text_file": "Файл TXT с рассказом",
                  "image_story": "Иллюстрация к рассказу"}
        widgets = {"title_story": TextInput(attrs={"size": "55"})}

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from .models import Story
from .forms import StoryForm
from .utilites import thousand_characters


#  blog home page - all stories with the paginator
# [rus] главная страница блога - показываются все рассказы с пагинатором
def blog(request):
    # users = User.objects.all()  # get users
    strs = Story.objects.get_queryset().order_by("-id")  # get stories
    paginator = Paginator(strs, 4)  # create paginator

    # Determining the page number for the paginator
    # [rus] Определение номера страницы для пагинатора
    if "page" in request.GET:
        page_number = request.GET["page"]
    else:
        page_number = 1

    page = paginator.get_page(page_number)  # get obj Page
    context = {"page": page, "stories": page.object_list}
    return render(request, 'blog.html', context)


# the page controller 'login'
# [rus] контроллер страницы 'входа'
class BlogLoginView(LoginView):
    template_name = "login.html"


# the page controller 'exit'
# [rus] контроллер страницы 'выхода'
class BlogLogoutView(LoginRequiredMixin, LogoutView):
    template_name = "logout.html"


# profile for the user who logged in: shows his stories
# [rus] профиль для пользователя (выполневшего вход): показывает его рассказы
@login_required
def profile(request):
    return render(request, "profile.html")


# controller-class that registers the user
# [rus] контроллер-класс регистрирующий пользователя
class RegisterUserView(CreateView):
    model = User
    template_name = "register_user.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("blog:register_done")


# displays a message about successful registration
# [rus] выводит сообщение об удачной регистрации
class RegisterDoneView(TemplateView):
    template_name = "register_done.html"

# Adding a new story
# [rus] Добавление нового рассказа
def add_story(request):
    if request.method == "POST":
        form = StoryForm(request.POST, request.FILES)  # the form accepts post and files requests
        if form.is_valid():
            s = form.save(commit=False)  # saving a form
            s.stories = request.user # adding the "stories" field to the form
            s.text_small = s.text_file.read().decode("utf-8")[:200] + "..."  # adding the "text_small" field to the form
            # s.save()  # saving a record to a database
            return redirect("blog:story_done")  # status=302
        else:
            form = StoryForm(request.POST, request.FILES)  # empty form
    else:
        form = StoryForm()  # empty form
    context = {"form": form}
    return render(request, "story_add.html", context)

# displays a message about the successful addition of the story
# [rus] выводит сообщение об успешном добавлении рассказа
def story_done(request):
    return render(request, "story_done.html")

# Story Page
# [rus] Страница рассказа
def page_story(request, id_story):
    story = Story.objects.get(id=id_story)
    text = story.text_file.read().decode("utf-8")
    context = {"story": story, "text": text}
    return render(request, "page_story.html", context)

main/views.py
from django.shortcuts import render

# home page
# [rus] главная страница сайта
def index(request):
    return render(request, "main/index.html")

visitka/views.py
from django.shortcuts import render

def visitka(request):
	context = {"quest": "Ответ 200"}
	return render(request, "visitka.html", context)

blog/templates/blog.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}


{% block title %}Блог писателей{% endblock %}
{% block namepage %}Блог{% endblock %}

{% block content %}
    <br>
    <div class="d-flex flex-row">
        <!-- Links -->
        <ul class="shadow">
            {% if user.is_authenticated %}
                <li class="nav-link"><a href="{% url 'blog:blog' %}">Все рассказы</a></li>
                <li class="nav-link"><a href="{% url 'blog:profile' %}">Мои рассказы</a></li>
                <li class="nav-link"><a href="{% url 'blog:add_story' %}">Добавить новый рассказ</a></li>
                <li class="nav-link"><a href="{% url 'blog:logout' %}">Выход</a></li>
            {% else %}
                <li class="nav-link"><a href="{% url 'blog:login' %}">Вход</a></li>
                <li class="nav-link"><a href="{% url 'blog:register' %}">Регистрация</a></li>
                <li class="nav-link"><a href="{% url 'blog:blog' %}">Все рассказы</a></li>
            {% endif %}
        </ul>

    {% block include_content %}
        <div class="container border rounded-top">
            <div class="row">
                <div class="col-sm">
                    <h2 align="center">Рассказы</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    {% for s in stories %}
                        <div class="row">
                            <div class="col-sm-4">
                                <img src="{{ s.image_story.url }}" class="img-thumbnail" alt="Иллюстрация к рассказу {{ s.title_story }}">
                            </div>
                            <div class="col-sm-8">
                                <div class="row">
                                    <div class="col-sm-8">
                                        Наименование рассказа: {{ s.title_story }}
                                    </div>
                                    <div class="col-sm-4">
                                        Автор: {{ s.get_author }} {{s.stories }}
                                    </div>
                                </div>
                                <hr>
                                <div class="row p-2">
                                    {{ s.text_small }} <a href="{% url "blog:page_story" id_story=s.id %}">Читать далее</a>
                                </div>
                            </div>
                        </div>
                        <hr><br>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page.has_previous %}
                                <a href="?page=1">&laquo; first</a>
                                <a href="?page={{ page.previous_page_number }}">previous</a>
                            {% endif %}
                            <span class="current">
                                Страница № {{ page.number }} of {{ page.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page.next_page_number }}">next</a>
                                <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
{% endblock %}

blog/templates/login.html
{% extends 'blog.html' %}
{% load bootstrap4 %}

{% block title %}Вход - Блог писателей{% endblock %}


{% block include_content %}
<div class="shadow w-100 p-5" align="center">
    <h2>Вход</h2><br>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход</p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form layout="horizontal" %}
            <input type="hidden" name="next" value="{{ next }}">
            {% buttons submit="Войти" %}{% endbuttons %}
        </form>
    {% endif %}
</div>
{% endblock %}

blog/templates/logout.html
{% extends 'blog.html' %}

{% block title %}Мои рассказы - Блог писателей{% endblock %}

{% block include_content %}
<h2>{{ user.username }} успешно выполнил выход.</h2>
{% endblock %}

blog/templates/page_story.html
{% extends "blog.html" %}
{% load bootstrap4 %}

{% block include_content %}
<div class="container border rounded">

<div class="row">
    <div class="col">
        <h2 align="center">
            {{ story.title_story }}
        </h2>
    </div>
</div>
    <hr>
<div class="row">
    <div class="col">
{# Описать картинку и рассказ #}
        <div class="alert visible-xs">
            <img src="{{ story.image_story.url }}" class="img-fluid">
        </div>
        <p class="text-justify">{{ text }}</p>
    </div>
</div>

</div>
{% endblock %}

blog/templates/profile.html
{% extends 'blog.html' %}

{% block title %}Мои рассказы - Блог писателей{% endblock %}

{% block include_content %}
<h2>Рассказы {{ user.username }}</h2>

<!-- FIXME сделать список из рассказов пользователя и пагинатор, максимум 10 рассказов -->
<p>Здесь будут рассказы</p>

{% endblock %}

blog/templates/register_done.html
{% extends 'blog.html' %}
{% load bootstrap4 %}

{% block title %}Завершене регистрации - Блог писателей{% endblock %}


{% block include_content %}
<div class="shadow w-100 p-5" align="center">
    <h2>Регистрация нового пользователя завершена.</h2><br>
    <p>На почту выслано письмо.</p>
</div>
{% endblock %}

blog/templates/register_user.html
{% extends 'blog.html' %}
{% load bootstrap4 %}

{% block title %}Регистрация - Блог писателей{% endblock %}


{% block include_content %}
<div class="shadow w-100 p-5" align="center">
    <h2>Регистрация нового пользователя.</h2><br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons submit="Зарегистрироваться" %}{% endbuttons %}
    </form>
</div>
{% endblock %}

blog/templates/story_add.html
{% extends "blog.html" %}
{% load bootstrap4 %}

{% block namepage %}Добавление рассказа{% endblock %}

{% block include_content %}
<div class="shadow w-100 p-5" align="center">
    <h2>Добавьте рассказ</h2><br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons submit="Добавить" %}{% endbuttons %}
    </form>
</div>
{% endblock %}

blog/templates/story_done.html
{% extends 'blog.html' %}
{% load bootstrap4 %}

{% block title %}Завершене добавление рассказа - Блог писателей{% endblock %}


{% block include_content %}
<div class="shadow w-100 p-5" align="center">
    <h2>Новый рассказ успешно добавлен.</h2><br>

</div>
{% endblock %}

main/templates/layout/base.html
{# load the tag Library #}
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Алексей Танаев</title>
    {# load CSS #}
    {% bootstrap_css %}
    {# My CSS #}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
</head>

<body class="container">
    {# My HTML #}
    <div class="jumbotron text-center" style="margin-bottom:0">
        <h1>Алексей Танаев</h1>
        <p>Этот сайт является портфолио, использовались фреймфорк Django и игровой движок Godot, векторная графика Moho.</p>
        <p class="mb-0">Вы находитесь в разделе: {% block namepage %}Резюме{% endblock %}</p>
    </div>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'main:index' %}">Резюме</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visitka:visitka' %}">Визитка</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blog' %}">Блог</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Магазин</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Игры</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    {# load JavaScript #}
    {% bootstrap_javascript jquery="full" %}
</body>

{#<div class="container">#}
{#    <div class="row">#}
{#        <div class="col">#}
{#            <footer class="modal-footer">#}
{#                <p class="text-center text-info pt-3 font-italic">&copy; AlexTan 2020</p>#}
{#            </footer>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

</html>

main/templates/main/index.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}Резюме{% endblock %}

{% block content %}
<div class="container" style="margin-top:30px">
        <div class="row">
            <div class="col-sm-4">
                <div class="img">
                    <img src="{% static 'media/AlexT.jpg' %}" alt="Photo AlexT.jpg" width="100%">
                </div>
                <hr class="d-sm-none">
            </div>
            <div class="col-sm-8">
                <h2>КОНТАКТНЫЕ ДАННЫЕ</h2><br>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm">
                            <b>Мобильный&nbsp;телефон:</b>
                        </div>
                        <div class="col-sm colortext">
                            +7(926)1411865
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <b>Электронная&nbsp;почта:</b>
                        </div>
                        <div class="col-sm colortext">
                            tanaev@bk.ru
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <b>Возраст:</b>
                        </div>
                        <div class="col-sm colortext">
                            41 год (28.12.1978)
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <b>Проживание:</b>
                        </div>
                        <div class="col-sm colortext">
                            Москва (метро Отрадное)
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <b>Ключевые навыки:</b>
                        </div>
                        <div class="col-sm colortext">
                            Python, Linux, Git, PosgreSQL, Django, ООП
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <b>Гражданство:</b>
                        </div>
                        <div class="col-sm colortext">
                            Россия
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm">
                            <b>Семейное&nbsp;положение:</b>
                        </div>
                        <div class="col-sm colortext">
                            Женат, дети (двое)
                        </div>
                        <div class="col-sm"></div>
                    </div>
                    <br>
                </div>
                <br>
                <h2>ОПЫТ РАБОТЫ</h2><br>
                <h5>Военная служба в Вооружённых Силах РФ, 1999 - 2007</h5>
                <p><ins>Должность:</ins> техник-оператор</p>
                <p><ins>Обязанности:</ins> выполнение видеосъемки, монтаж видеоматериала, компьютерная графика. Написание сценариев для репортажей.</p>
                <h5>Работа в различных мелких компаниях и на фрилансе, 2007 - 2016</h5>
                <p><ins>Обязанности:</ins> Компьютерная графика, монтаж видео, фотография, менеджмент, составление и подписание договоров с клиентами.</p>
                <h5>Гражданская служба в Главном Вычислительном Центре Вооружённых Силах РФ, 2016 - настоящее время</h5>
                <p><ins>Должность:</ins> инженер-программист</p>
                <p><ins>Обязанности:</ins> написание скриптов, GUI, программ на языка Python, знание алгоритмов и паттернов проектирования. PostgreSQL, SQLite.</p>
            </div>
        </div>
    </div>
{% endblock %}

visitka/templates/visitka.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}

{% block title %}Сайт визитка{% endblock %}
{% block namepage %}Одностраничный сайт{% endblock %}

{% block content %}
{{ quest }}
{% endblock %}